[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["Alpha Chen <alpha.chen@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.2.0"
pest = "2.0"
pest_derive = "2.0"
regex = "1"
