[package]
name = "advent_of_code_2016"
version = "0.1.0"
authors = ["Alpha Chen <alpha.chen@gmail.com>"]

[dependencies]
error-chain = "0.7"
regex = "0.1"
rust-crypto = "0.2"

[profile.release]
debug = true
